### ISSUE TITLE
Crash when detecting EMV reader

### ISSUE THREAD

**Issue by sammcewan** [PayPal-Mobile/ios-here-sdk-dist#22]
Have connected both EMV readers and during detection we get a crash in:
`-[PPHBondReaderDelegate getUpdateInformation] `

The reported crash is:
`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]'`

**Comment by vinodhsundararajan** [comment]
@sammcewan I am aware of this issue and we are currently working on a fix that should be released soon. I don't have an exact ETA - we are going through our testing now and will keep you posted as soon as the fix is available

**Comment by sammcewan** [comment]
@vinodhsundararajan thanks. Looking forward to moving ahead with the integration.

**Comment by sammcewan** [comment]
@vinodhsundararajan presume this is still an issue in 1.4.9? Same crasher exists.

**Comment by Damavik** [comment]
Exactly the same crash is still reproducible (with the latest commit c74135c). I only noted that NO crash occurs when audio jack reader has been plugged in before activating (pairing) BT reader. But if no readers attached before activating BT one then crash occurs constantly.
